services:
  p4d:
    container_name: "p4d"
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    hostname: perforce
    environment:
      - P4_PORT=ssl:1666
      - P4_NAME=perforceserver
      - P4_USER=${P4_USER}
      - P4_EMAIL=${P4_EMAIL}
      - P4_FULL_NAME=${P4_FULL_NAME}
      - P4_PASS=${P4_PASS}
    volumes:
      - serverdata:/metadata
      - serverlibrary:/library
      - serverjournals:/journals
      - servercheckpoints:/checkpoints
      - ssl:/ssl
    ports:
      - "1666:1666"

volumes:
  serverdata:
  serverlibrary:
  servercheckpoints:
  serverjournals:
  ssl:
