version: '3.9'

services:
  p4d:
    image: perforce/helix-core
    container_name: perforce-server
    ports:
      - "1666:1666"
    environment:
      - P4PORT=1666
      - P4USER=super
      - P4ROOT=/perforce/depots
    volumes:
      - ./depot:/perforce/depots
      - ./metadata:/perforce/metadata
    restart: unless-stopped

  swarm:
    image: perforce/helix-swarm
    container_name: perforce-swarm
    ports:
      - "8080:80"
    environment:
      - SWARM_HOSTNAME=localhost:8080
      - P4PORT=p4d:1666
      - SWARM_ADMIN_USER=super
    depends_on:
      - p4d
    restart: unless-stopped
