services:
  p4d:
    container_name: "p4d"
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    hostname: perforce
    environment:
      - P4PORT=ssl:1666
      - P4NAME=perforceserver
      - P4USER=${P4USER}
      - P4EMAIL=${P4EMAIL}
      - P4FULLNAME=${P4FULLNAME}
      - P4PASS=${P4PASS}
    volumes:
      - serverdata:/metadata
      - serverlibrary:/library
      - serverjournals:/journals
      - servercheckpoints:/checkpoints
      - ssl:/ssl
    ports:
      - "1666:1666"

volumes:
  serverdata:
  serverlibrary:
  servercheckpoints:
  serverjournals:
  ssl:
