name: Deploy Perforce Server

on:
  workflow_dispatch:

env:
  DEPLOY_DIR: /srv/perforce
  COMPOSE_FILE: docker-compose.yml

jobs:

  upload:
    name: Upload Docker Compose file
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Ensure docker-compose file is present
        run: ls -la ${{ env.COMPOSE_FILE }}

      - name: Upload docker-compose.yml to server
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ vars.SSH_HOST }}
          username: ${{ vars.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          source: "${{ env.COMPOSE_FILE }}"
          target: "${{ env.DEPLOY_DIR }}"

  deploy:
    name: Deploy Perforce Stack
    runs-on: ubuntu-latest
    needs: upload

    steps:
      - name: Run docker compose on server
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ vars.SSH_HOST }}
          username: ${{ vars.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            cd ${{ env.DEPLOY_DIR }}
            docker compose -f ${{ env.COMPOSE_FILE }} down || true
            docker compose -f ${{ env.COMPOSE_FILE }} up -d
