name: Deploy Perforce Server

on:
  workflow_dispatch:

env:
  IMAGE_NAME: perforce-server
  DEPLOY_DIR: /srv/perforce
  COMPOSE_FILE: docker-compose.yml

jobs:
  upload:
    name: Upload Files to Server
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Upload Docker Compose files
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ vars.SSH_HOST }}
          username: ${{ vars.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          source: |
            docker-compose.yml
            Dockerfile
            docker-entrypoint.sh
          target: ${{ env.DEPLOY_DIR }}

  deploy:
    name: Deploy with Docker Compose
    runs-on: ubuntu-latest
    needs: upload

    steps:
      - name: Launch container via SSH
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ vars.SSH_HOST }}
          username: ${{ vars.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            cd ${{ env.DEPLOY_DIR }}
            chmod +x docker-entrypoint.sh
            docker-compose down || true
            docker-compose build
            docker-compose up -d
